import { Readable } from "node:stream";
import { NextResponse } from "next/server";
import { getCurrentUser } from "@/lib/auth";
import { isSafeObjectPath } from "@/lib/charts";
import { getDb } from "@/lib/db/pool";
import { CHART_BUCKET_ID, chartBucket } from "@/lib/storage";

export const runtime = "nodejs";

/**
 * Serves a chart SVG from the private bucket to a signed-in user.
 *
 * Defense in depth against reading arbitrary objects: the path must be a
 * well-formed relative path AND be registered in stored_objects (written only
 * by the pipeline after a successful upload). Objects are immutable and
 * content-addressed, so the response can be cached by the browser.
 */
export async function GET(_request: Request, { params }: { params: Promise<{ path: string[] }> }) {
  const user = await getCurrentUser();
  if (!user) return NextResponse.json({ error: "unauthenticated" }, { status: 401 });

  const objectPath = (await params).path.map(decodeURIComponent).join("/");
  if (!isSafeObjectPath(objectPath)) return NextResponse.json({ error: "not_found" }, { status: 404 });

  const registered = await getDb().one(`select 1 as ok from stored_objects where bucket = $1 and name = $2`, [CHART_BUCKET_ID, objectPath]);
  if (!registered) return NextResponse.json({ error: "not_found" }, { status: 404 });

  const file = chartBucket().file(objectPath);
  const [exists] = await file.exists();
  if (!exists) return NextResponse.json({ error: "not_found" }, { status: 404 });

  return new Response(Readable.toWeb(file.createReadStream()) as ReadableStream, {
    headers: {
      "Content-Type": "image/svg+xml",
      "Cache-Control": "private, max-age=3600, immutable",
      "X-Content-Type-Options": "nosniff",
      // Charts are generated by us, but never let an SVG run script if opened directly.
      "Content-Security-Policy": "default-src 'none'; style-src 'unsafe-inline'; sandbox",
    },
  });
}
